services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bookstore


volumes:
  mongodb_data: